global.factos = [
    "You are the reason there are instructions on shampoo bottles.",
    "If you were a book, you'd be the one nobody wants to read.",
    "Your life is like a TV show nobody watches.",
    "You're like a typo: just there to ruin everything.",
    "If you were a product, you'd be the one on sale because nobody buys it.",
    "You're a reminder of what not to do in life.",
    "Your existence is as relevant as a file in the recycle bin.",
    "If you were a dish, you'd be one nobody wants to try.",
    "You're the reason men are afraid of commitment.",
    "Your personality is like antivirus software: nobody wants to install it.",
    "You're proof that natural selection can fail.",
    "If you were a color, you'd be gray: boring and lifeless.",
    "Your life is like a bad movie: nobody wants to see the ending.",
    "You're like a bad joke: always making people uncomfortable.",
    "If you were an animal, you'd be the pet nobody wants to adopt.",
    "Your sense of humor is like bad Wi-Fi: no connection.",
    "You're like a wilted plant: just taking up space.",
    "If you were a computer virus, you'd be one that causes more problems than solutions.",
    "Your image is the reason mirrors are covered.",
    "You're the perfect example of how not to live life.",
    "If you were a day of the week, you'd be Monday: everyone hates you.",
    "You're the reason people don't believe in true love.",
    "Your life is a meme, but nobody laughs.",
    "If you were an app, you'd be one nobody wants to download.",
    "You're like a shadow: always there, but not welcome.",
    "Your brain is like a full hard drive: can't store any more.",
    "You're like a derailed train: just causing chaos.",
    "If you were weather, you'd be a storm: dark and destructive.",
    "You're like a chain message: nobody wants you, but everyone gets you.",
    "Your life is like a puzzle with pieces that never fit.",
    "If you were a movie, you'd be a sequel nobody asked for."
];
